program: w_use_wandb_2.py
method: grid
metric:
  goal: minimize
  name: mae
parameters:
  conv:
    values: [128]
  learning_rate:
    values: [0.0001]
  epoch: 
    value: 50
  optimizer:
    values: ['adam']
  activation:
    values:  ['swish','relu','sigmoid', 'tanh', 'elu' ]
  batch_size:
    values: [64]



